# Our happy bunch of tripsters, same as in DefaultTripsters.
---

tripsters:
    - name: gauss 
      description: Ventures in numberland.
      cycle: 
        - 0 (mod 5)
        - 1 (mod 5)
        - 2 (mod 5)
        - 3 (mod 5)
        - 4 (mod 5)
        
    - name: hipster
      description: Tours South Africa.
      cycle: [Cape Town, Knysna, Durbs, Jozi]